[package]
name = "dioxus-modal-macros"
version = "0.2.0"
edition = "2024"
description = "Macros for dioxus-modal"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }
